name: shakepin
description: "A simple overlay window to hold files."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  desktop_drop:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      path: packages/desktop_drop
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  macos_haptic_feedback: ^1.0.0
  signals_flutter: ^5.3.0
  super_drag_and_drop: ^0.8.18
  window_manager:
    path: ./packages/window_manager
  cupertino_icons:
  macos_window_utils: ^1.5.0
  fluentui_system_icons: ^1.1.251
  macos_ui: ^2.0.7
  super_context_menu: ^0.8.18
  tray_manager: ^0.2.3
  screen_retriever: ^0.1.9
  collection: ^1.18.0
  # desktop_multi_window:
  #   path: ./packages/desktop_multi_window
  # desktop_multi_window:
  #   path: ./packages/rustdesk_desktop_multi_window

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/tray_icon.png

icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    macos:
      enable: true
