name: shakepin
description: "Pin, minify, and archive your files with unparalleled ease"
publish_to: 'none'
version: 0.2.13
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  macos_ui: ^2.0.9
  shared_preferences: ^2.3.2
  fluentui_system_icons: ^1.1.257
  super_context_menu: ^0.8.22
  macos_haptic_feedback: ^1.0.0
  cupertino_icons: ^1.0.8
  libcaesium_dart:
    path: ../libcaesium_dart
  path: any
  extended_text: ^14.1.0
  super_sliver_list: ^0.4.1
  path_provider: ^2.1.4
  url_launcher: ^6.1.10
  package_info_plus: ^8.0.2
  lukehog: ^0.4.1+2
  ffmpeg_kit_flutter_video: ^6.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0
  flutter_oss_licenses: ^3.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/tray_icon.png
icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    macos:
      enable: true
