name: shakepin
description: "Pin, minify, and archive your files with unparalleled ease"
publish_to: "none"
version: 0.4.0
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  macos_ui: ^2.0.9
  shared_preferences: ^2.3.2
  fluentui_system_icons: ^1.1.257
  super_context_menu: ^0.8.22
  macos_haptic_feedback: ^1.0.0
  cupertino_icons: ^1.0.8
  libcaesium_dart:
    git:
      url: https://github.com/foamify/libcaesium_dart.git
  path: any
  extended_text: ^15.0.2
  super_sliver_list: ^0.4.1
  path_provider: ^2.1.4
  url_launcher: ^6.2.1
  lukehog: ^0.4.1+2
  gradient_borders: ^1.0.1
  package_info_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/package_info_plus/package_info_plus
  auto_updater: ^1.0.0
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.1.2
  crypto: ^3.0.6
  file_picker: ^8.3.1
  window_manager: ^0.4.3
  flutter_acrylic: ^1.1.4
  screen_retriever: ^0.2.0
  tray_manager: ^0.3.2
  dotted_border: ^2.1.0
  pointer_lock:
    git: https://github.com/helgoboss/pointer_lock.git
  video_player: ^2.9.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0
  flutter_oss_licenses: ^3.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/tray_icon.png
icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    macos:
      enable: true
